import { Paper, PaperOutline } from '@/types';
import { CitationFormat } from './exportDocx';

/** Escape special LaTeX characters to guarantee zero compilation errors */
export function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

/** Sanitize paper ID to valid LaTeX citation key (letters, digits, underscores) */
export function latexCiteKey(paper: Paper): string {
  const author = (paper.authors[0] || 'ref').split(' ').pop()?.toLowerCase().replace(/[^a-z0-9]/g, '') || 'ref';
  const year = paper.published ? paper.published.split('-')[0] : '2026';
  const idClean = paper.id.replace(/[^a-zA-Z0-9]/g, '_');
  return `${author}${year}_${idClean}`;
}

export interface LatexExportInput {
  outline: PaperOutline;
  sections: Array<{ title: string; text: string }>;
  citedPapers: Paper[];
  citationFormat: CitationFormat;
}

export function buildLatexDocument({
  outline,
  sections,
  citedPapers,
  citationFormat,
}: LatexExportInput): string {
  const isIEEE = citationFormat === 'ieee';

  // Build citation map: paper.id -> citeKey
  const keyMap = new Map<string, string>();
  citedPapers.forEach((p) => {
    keyMap.set(p.id, latexCiteKey(p));
  });

  const resolveLatexSection = (text: string): string => {
    let out = text;
    // Replace {{paperId}} with \cite{key}
    citedPapers.forEach((p) => {
      const k = keyMap.get(p.id) || p.id;
      const placeholder = `{{${p.id}}}`;
      out = out.split(`(${placeholder})`).join(`~\\cite{${k}}`);
      out = out.split(placeholder).join(`~\\cite{${k}}`);
    });

    // Replace any remaining {{...}} placeholders
    out = out.replace(/\{\{([^}]+)\}\}/g, (_m, id: string) => {
      const match = citedPapers.find(
        (p) => p.id === id || p.title.toLowerCase().includes(id.toLowerCase())
      );
      const k = match ? keyMap.get(match.id) || match.id : 'ref';
      return `~\\cite{${k}}`;
    });

    // Clean up doubled cite commands or parens
    out = out.replace(/\(~?\\cite\{([^}]+)\}\)/g, '~\\cite{$1}');
    out = out.replace(/~{2,}\\cite/g, '~\\cite');

    // Split into paragraphs
    return out
      .split(/\n{2,}/)
      .map((p) => p.trim())
      .filter(Boolean)
      .join('\n\n');
  };

  const cleanTitle = escapeLatex(outline.title || 'PaperPilot Manuscript');

  // Separate abstract if present
  const abstractSec = sections.find((s) => s.title.toLowerCase().includes('abstract'));
  const bodySections = sections.filter((s) => !s.title.toLowerCase().includes('abstract'));

  const bibItems = citedPapers.map((p, i) => {
    const key = keyMap.get(p.id) || `ref_${i + 1}`;
    const authorsStr = escapeLatex(p.authors.join(', '));
    const titleStr = escapeLatex(p.title);
    const year = p.published ? p.published.split('-')[0] : '2026';
    const arxivId = p.id;
    return `\\bibitem{${key}}\n${authorsStr}, "${titleStr}," \\textit{arXiv preprint arXiv:${arxivId}}, ${year}.`;
  });

  if (isIEEE) {
    return `% ==============================================================================
% IEEE Conference Template — Generated by PaperPilot (WebMCP Academic Studio)
% Compiles cleanly on Overleaf or with pdflatex
% ==============================================================================
\\documentclass[conference]{IEEEtran}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath,amssymb,amsfonts}
\\usepackage{algorithmic}
\\usepackage{graphicx}
\\usepackage{textcomp}
\\usepackage{xcolor}
\\usepackage{cite}
\\usepackage{hyperref}
\\hypersetup{colorlinks=true, linkcolor=black, citecolor=blue, urlcolor=blue}

\\begin{document}

\\title{${cleanTitle}}

\\author{
  \\IEEEauthorblockN{Anonymous Author}
  \\IEEEauthorblockA{\\textit{Department of Computer Science} \\\\
  \\textit{Institution / University} \\\\
  Academic Research Manuscript}
}

\\maketitle

${
  abstractSec
    ? `\\begin{abstract}
${resolveLatexSection(abstractSec.text)}
\\end{abstract}

\\begin{IEEEkeywords}
WebMCP, autonomous agents, academic literature review, agent-native systems.
\\end{IEEEkeywords}
`
    : ''
}

${bodySections
  .map(
    (sec) => `\\section{${escapeLatex(sec.title)}}
${resolveLatexSection(sec.text)}`
  )
  .join('\n\n')}

\\begin{thebibliography}{${Math.max(bibItems.length, 9)}}
${bibItems.join('\n\n')}
\\end{thebibliography}

\\end{document}
`;
  }

  // Standard APA / Academic Article template
  return `% ==============================================================================
% Academic Preprint Template — Generated by PaperPilot (WebMCP Academic Studio)
% Compiles cleanly on Overleaf or with pdflatex
% ==============================================================================
\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[margin=1in]{geometry}
\\usepackage{amsmath,amssymb}
\\usepackage{cite}
\\usepackage{booktabs}
\\usepackage{hyperref}
\\hypersetup{colorlinks=true, linkcolor=blue, citecolor=blue, urlcolor=blue}

\\title{\\textbf{${cleanTitle}}}
\\author{Anonymous Author \\thanks{Draft prepared and reviewed with PaperPilot.}}
\\date{\\today}

\\begin{document}

\\maketitle

${
  abstractSec
    ? `\\begin{abstract}
\\noindent ${resolveLatexSection(abstractSec.text)}
\\end{abstract}
\\vspace{1em}
`
    : ''
}

${bodySections
  .map(
    (sec) => `\\section{${escapeLatex(sec.title)}}
${resolveLatexSection(sec.text)}`
  )
  .join('\n\n')}

\\begin{thebibliography}{${Math.max(bibItems.length, 9)}}
${bibItems.join('\n\n')}
\\end{thebibliography}

\\end{document}
`;
}
